baseURL = 'http://muja.dev/'
languageCode = 'en-us'
title = 'Muja Siyam'
theme = 'coder'
# site info
defaultContentLanguage = 'en'
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
disqusShortname = "mujasiyam"

[params]
author = 'Muja Siyam'
description = 'Muja Siyam personal website'
keywords = 'blog,developer,personal'
info = ['Full Stack DevSecOps', 'Magician']
avatarURL = "images/avatar.jpg"
gravatar = "contact@muja.dev"
dateFormat = "January 2, 2006"
since = 2012
