baseURL = 'http://muja.dev/'
languageCode = 'en-us'
title = 'Muja Siyam'
theme = 'coder'
# site info
defaultContentLanguage = 'en'
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
disqusShortname = "mujasiyam"

[params]
author = 'Muja Siyam'
description = 'Muja Siyam personal website'
keywords = 'blog,developer,personal'
info = ['Full Stack DevSecOps', 'Magician']
avatarURL = "images/avatar.jpg"
gravatar = "contact@muja.dev"
dateFormat = "January 2, 2006"
since = 2012
# Right To Left, language support
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = 'auto'
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []