baseURL = 'http://muja.dev/'
languageCode = 'en-us'
title = 'Muja Siyam'
theme = 'coder'
# site info
defaultContentLanguage = 'en'
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
disqusShortname = "mujasiyam"

